sudo: false
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.3.1
before_install:
  - "gem install bundler -v '~> 1.12'"
bundler_args: "--jobs=2"
cache: bundler
script:
  - "bundle exec rspec"
